### PR TITLE
increase max line length in ini files

### LINKED ISSUE #425: AllowedNodeNames limited to number of nodes?
## Describe the bug
Looking to test hirte in different scenarios and scales, I tried to run hirte with a bunch of agent nodes, like 50 but hirte config seems to block after some nodes.

It works until the node24:
```
# cat /etc/hirte/hirte.conf
# This is the configuration file for hirte manager.
#
# All available options are described in hirte.conf man page file provided by hirte package.
#

[hirte]

#
# A comma separated list of unique hirte-agent names. Only nodes with names mentioned in the list can connect to hirte
# manager. These names are defined in the agent's configuration file under the `NodeName` option.
# (see `hirte-agent.conf(5)`).
AllowedNodeNames=control,node1,qm.control,node2,node3,node4,node5,node6,node7,node8,node9,node10,node11,node12,node13,node14,node15,node16,node17,node18,node19,node20,node21,node22,node23,node24
#
# The port the manager listens on to establish connections with the hirte agents.
ManagerPort=842

#
# The level used for logging. Supported values are: DEBUG, INFO, WARN and ERROR.
LogLevel=INFO

#
# The target where logs are written to. Supported values are: journald and stderr.
LogTarget=stderr

#
# If this flag is set to true, no logs are written by hirte.
#LogIsQuiet=false
```

Added the `node25` and hirte manager dont start:
```
# ./builddir/src/manager/hirte -c /etc/hirte/hirte.conf
Error loading configuration file '/etc/hirte/hirte.conf': 'Unknown error -13'.
```

The config:
```
# This is the configuration file for hirte manager.
#
# All available options are described in hirte.conf man page file provided by hirte package.
#

[hirte]

#
# A comma separated list of unique hirte-agent names. Only nodes with names mentioned in the list can connect to hirte
# manager. These names are defined in the agent's configuration file under the `NodeName` option.
# (see `hirte-agent.conf(5)`).
AllowedNodeNames=control,node1,qm.control,node2,node3,node4,node5,node6,node7,node8,node9,node10,node11,node12,node13,node14,node15,node16,node17,node18,node19,node20,node21,node22,node23,node24,node25
#
# The port the manager listens on to establish connections with the hirte agents.
ManagerPort=842

#
# The level used for logging. Supported values are: DEBUG, INFO, WARN and ERROR.
LogLevel=INFO

#
# The target where logs are written to. Supported values are: journald and stderr.
LogTarget=stderr

#
# If this flag is set to true, no logs are written by hirte.
#LogIsQuiet=false
```

Trying to load the manager:
```
# ./builddir/src/manager/hirte -c /etc/hirte/hirte.conf
Error loading configuration file '/etc/hirte/hirte.conf': 'Unknown error -13'.

# ./builddir/src/manager/hirte -v
0.5.0
```

### PR DESCRIPTION
**Pull request by engelmi**
This PR increases the maximum line length when reading ini files. 
When reading hirte configuration files, the `AllowedNodeNames` entry might get quite long. In order to prevent cutting off the line line reading (and, subsequently, failing) as well as not require to much memory, lets increase the maximum length to a reasonable number. 

Fixes: #425

### CODE REVIEW

File: src/libhirte/ini/ini.h [hunk 1]
```diff
@@ -109,7 +109,7 @@ INI_API int ini_parse_string(const char *string, ini_handler handler, void *user
 /* Maximum line length for any line in INI file (stack or heap). Note that
    this must be 3 more than the longest line (due to '\r', '\n', and '\0'). */
 #ifndef INI_MAX_LINE
-#        define INI_MAX_LINE 200
+#        define INI_MAX_LINE 1024
```
Comment (rhatdan) [inline src/libhirte/ini/ini.h]: This still seems arbitrarily small.  Max DNS name size is 255, if you have 4 nodes each with a QM, that would be 8 node definition + separators would get you to 2040+ chars.

Do we have to have a constant, or could we allocate the buffer on the fly?

Comment (engelmi) [reply src/libhirte/ini/ini.h]: I agree, its still quite small. In https://github.com/containers/hirte/issues/425#issuecomment-1661693665 I explained why dynamic allocating is not really working out of the box. I'll have a look at it and see if I can write a custom reader function.  

_Update:_ After checking briefly, it seems that implementing a custom reader that wraps `getline` enables us to achive this. It still uses `INI_INITIAL_ALLOC=200` as the initial size, but is able to allocate more memory if needed - and frees it properly (when setting `INI_USE_STACK=0` so the library uses a "dynamic" approach). I reset the constant to its previous value as well. 
Could you have another look? @rhatdan

**Comment by rhatdan** [comment]
Can you add a test with a very long line to make sure this works fine.

**Comment by engelmi** [comment]
> Can you add a test with a very long line to make sure this works fine.

Good point! I added an integration test for it. I am also checking with valgrind.

File: src/libhirte/ini/ini.c [hunk 2]
```diff
@@ -257,9 +257,21 @@ int ini_parse_stream(ini_reader reader, void *stream, ini_handler handler, void
         return error;
 }
 
+/*
+Hirte's custom reader to read a line with arbitrary length.
+This function requires INI_USE_STACK=0.
+*/
+char *dynamic_reader(char *str, int num, void *stream) {
```
Comment (mwperina) [inline src/libhirte/ini/ini.c]: We have copied this file from https://github.com/benhoyt/inih so it would be better to leave untouched. Could you please create another C file in the same directory with our customized methods?

File: src/libhirte/ini/ini.h [hunk 3]
```diff
@@ -103,7 +103,7 @@ INI_API int ini_parse_string(const char *string, ini_handler handler, void *user
 
 /* Nonzero to use stack for line buffer, zero to use heap (malloc/free). */
 #ifndef INI_USE_STACK
-#        define INI_USE_STACK 1
+#        define INI_USE_STACK 0
```
Comment (mwperina) [inline src/libhirte/ini/ini.h]: Wouldn't it be better to pass `-DINI_USE_STACK=0` into the project build rather than modifying source code which we copied from different project?

https://github.com/benhoyt/inih/blob/master/README.md#memory-options

File: src/libhirte/ini/ini.c (hunk 2 above)
Comment (engelmi) [reply src/libhirte/ini/ini.c]: Sure, I can move it. But using valgrind I also found a memory allocation issue with the solution - the inih library is rather hard to extend in this regards. I'll need to take a deeper look into that and, if I can't fix it, we'll have to fallback to a large enough buffer.

Comment (engelmi) [reply src/libhirte/ini/ini.c]: Edit: The `ini_parse_file` I need to change nevertheless, since it only allows to pass in a custom handler.

Comment (mwperina) [reply src/libhirte/ini/ini.c]: > Sure, I can move it. But using valgrind I also found a memory allocation issue with the solution - the inih library is rather hard to extend in this regards. I'll need to take a deeper look into that and, if I can't fix it, we'll have to fallback to a large enough buffer.

The original project https://github.com/benhoyt/inih is active, so could you please retry with the latest and if the issue still exists, could you please report there? And maybe even post a fix if you know how to fix it?

**Comment by engelmi** [comment]
@rhatdan @mwperina 
I just did an overhaul of this PR as I figured out that `inih` supports multiline, which basically solves our issue. So instead of
```bash
AllowedNodeNames=laptop,pi,node0,node1,node2,node3,node4,node5,node6,node7,node8,node9,node10,node11,node12,node13,node14,node15,node16,node17,node18,node19,node20,node21,node22,node23,node24,node25,node26,node27,node28,node29,node30,node31,node32,node33,node34,node35,node36,node37,node38,node39,node40,node41,node42,node43,node44,node45,node46,node47,node48,node49
```
one would have
```bash
AllowedNodeNames=laptop,pi,node0,node1,node2,node3,node4,node5,node6,node7,node8,node9,node10,node11,node12,node13,node14,node15,node16,node17,
  node18,node19,node20,node21,node22,node23,node24,node25,node26,node27,node28,node29,node30,node31,node32,node33,node34,node35,node36,node37,
  node38,node39,node40,node41,node42,node43,node44,node45,node46,node47,node48,node49
```
Which is also more intuitive, I think. 

Unfortunately, I found out that we are just overriding values from multiple lines - so having a "last one wins" implementation. I changed this PR to support this, adjusted the test and updated the inline documentation in the config to mention this limit. I also increased the line limit from 200 to 500 usable characters (520 due to the key name).
Could you have another look?

**Review by mwperina — APPROVED** [review]
LGTM

**Comment by mwperina** [comment]
We should also mentione the max line size and the ability of having multiple lines for a value in the man pages and configuration file examples

**Comment by engelmi** [comment]
> We should also mentione the max line size and the ability of having multiple lines for a value in the man pages and configuration file examples

Good point! I added a few sentences in the `hirte` and `hirte-agent` man pages within the `Format` section and added examples.

File: doc/docs/configuration.md [hunk 4]
```diff
@@ -18,3 +20,14 @@ configuration has the highest priority and all defined settings will override pr
...
 For a list of supported options incl. an explanation please refer to the
 the MAN pages for [hirte(5)](./man/hirte_conf.md) and [hirte-agent(5)](./man/hirte_agent_conf.md).
+
+## Maximum line length
+
+The maximum line length supported by hirte is 500 characters. If the characters of any key-value pair exceeds this, use
+multiple, indented lines. For example, a large number of node names in the `AllowedNodeNames` field can be split like this:
+
+```bash
+AllowedNodeNames=node0,node1,node2,node3,node4,node5,node6,node7,node8,node9,node10,node11,node12,node13,node14,node15,node16,node17,
```
Comment (mwperina) [inline doc/docs/configuration.md]: I'd prefer simpler example, following seems to me descriptive enough
```
AllowedNodeNames=node1,
node2,
node3
```

File: doc/man/hirte.conf.5.md [hunk 5]
```diff
@@ -64,6 +66,20 @@ LogTarget=journald
...
 
+Using a value that is continued on multiple lines:
+
+```
+[hirte]
+ManagerPort=842
+AllowedNodeNames=agent-007,
+   agent-123,
+   agent-456,
+   agent-789,
```
Comment (mwperina) [inline doc/man/hirte.conf.5.md]: Hmm, wouldn't the `,` after the last node causing parsing error?

File: doc/docs/configuration.md (hunk 4 above)
Comment (engelmi) [reply doc/docs/configuration.md]: Changed

File: doc/man/hirte.conf.5.md (hunk 5 above)
Comment (engelmi) [reply doc/man/hirte.conf.5.md]: No. The `,` is independent of the ini parsing. And later on when splitting the names by the `,` symbol we check if the node name is empty or NULL. The `cfg_dump` is a bit misleading (it just takes the read, full string), but via `list_nodes()` API call on the manager this can be verified.

Comment (mwperina) [reply doc/man/hirte.conf.5.md]: OK, that's great. But I'd probably not put the `,` if we don't need it there

**Review by mwperina — APPROVED** [review]
LGTM

File: doc/man/hirte.conf.5.md (hunk 5 above)
Comment (engelmi) [reply doc/man/hirte.conf.5.md]: I agree. Removed it.
