### PR TITLE
Fix lcov coverage collection for integration tests

### LINKED ISSUE #1088: Investigate lcov coverage drop for cs10
For the CentOS Stream 10 integration test runs the collected coverage reported has been dropped in https://github.com/eclipse-bluechi/bluechi/pull/1087 by 7%. This could be due to a mismatch of the lcov (geninfo) and gcc (gcov) version in cs10 or something else. Needs investigation. 

Related coverall: https://coveralls.io/builds/74496868
Related PR: https://github.com/eclipse-bluechi/bluechi/pull/1087
Related GH CI summary: https://github.com/eclipse-bluechi/bluechi/actions/runs/16111446610?pr=1087
Artifacts from the CI summary:
- [coverage-artifacts-html.zip](https://github.com/user-attachments/files/21121031/coverage-artifacts-html.zip)
- [coverage-artifacts-info.zip](https://github.com/user-attachments/files/21121033/coverage-artifacts-info.zip)
- [rpm-artifacts.zip](https://github.com/user-attachments/files/21121034/rpm-artifacts.zip)
- [tmt-artifacts.zip](https://github.com/user-attachments/files/21121032/tmt-artifacts.zip)

Relates to https://github.com/eclipse-bluechi/bluechi/issues/1084

### PR DESCRIPTION
**Pull request by ArtiomDivak**
Fix geninfo path mapping issues that prevented proper coverage collection during integration tests. The issue was caused by hardcoded build paths in .gcno files that didn't match the runtime container paths.

Changes made:
- Add python3-wheel dependency to build-base container
- Fix geninfo path substitution in gather-code-coverage.sh using --substitute
- Replace build-time paths with runtime container paths dynamically

This resolves the coverage drop issues and enables successful coverage collection during integration tests with proper path mapping.

Closes https://github.com/eclipse-bluechi/bluechi/issues/1088

### CODE REVIEW

File: tests/containers/integration-test-local [hunk 1]
```diff
@@ -8,6 +8,7 @@ RUN dnf install --repo bluechi-rpms \
         --repofrompath bluechi-rpms,file:///tmp/bluechi-rpms/ \
         --nogpgcheck \
         --nodocs \
+        --skip-broken \
```
Comment (engelmi) [inline tests/containers/integration-test-local]: We shouldn't add `--skip-broken` here. What is the error you get when building without this flag?

File: tests/scripts/gather-code-coverage.sh [hunk 2]
```diff
@@ -7,6 +7,7 @@
 
 # First parameter is the name of the generated info file
 INFO_FILE=${1:-coverage.info}
+SRC_DIR="~/rpmbuild/BUILD/bluechi-1.2.0"
```
Comment (engelmi) [inline tests/scripts/gather-code-coverage.sh]: We need to replace the hardcoded version here `bluechi-1.2.0` with a parameter. Could you have look at this? @ArtiomDivak

File: tests/containers/integration-test-local (hunk 1 above)
Comment (ArtiomDivak) [reply tests/containers/integration-test-local]: Seems to me like we need to update the repos in quay.io/bluechi/integration-test-base:stream10
If I add `RUN dnf update -y selinux-policy selinux-policy-base selinux-policy-targeted || true`
to integration-test.yml it will work

Comment (engelmi) [reply tests/containers/integration-test-local]: We already do a `dnf upgrade` in the [integration-test-base image here](https://github.com/eclipse-bluechi/bluechi/blob/main/containers/integration-test-base#L7). The tests will also fail if the version is not the latest due to the requirements in the bluechi packages. I rebuild the base container ealier today:
https://github.com/eclipse-bluechi/bluechi/actions/runs/16718593341

Why do you think updating the selinux packages resolves this?

File: tests/scripts/gather-code-coverage.sh (hunk 2 above)
Comment (ArtiomDivak) [reply tests/scripts/gather-code-coverage.sh]: Changed to dynamic version of bluechi

File: tests/scripts/gather-code-coverage.sh [hunk 3]
```diff
@@ -7,6 +7,17 @@
 
 # First parameter is the name of the generated info file
 INFO_FILE=${1:-coverage.info}
+BLUECHI_VERSION=${2:-unknown}
+
+# Find the bluechi debug directory dynamically to extract version
+BLUECHI_DEBUG_DIR=$(find /usr/src/debug -maxdepth 1 -type d -name 'bluechi-*' | head -1)
+if [ -z "$BLUECHI_DEBUG_DIR" ]; then
+    echo "Error: No bluechi-* directory found in /usr/src/debug"
```
Comment (engelmi) [inline tests/scripts/gather-code-coverage.sh]: NIT:
```suggestion
    echo "Error: No debug source files found for BlueChi"
```

File: .github/workflows/integration-tests.yml [hunk 4]
```diff
@@ -103,11 +103,13 @@ jobs:
         id: run-tests
         run: |
           cd tests
+          BLUECHI_VERSION=$(../build-scripts/version.sh)
```
Comment (engelmi) [inline .github/workflows/integration-tests.yml:106]: I am wondering if we can't just export the BlueChi version in the tmt prepare step:
https://github.com/eclipse-bluechi/bluechi/blob/main/tests/plans/container.fmf#L16-L20
Either as part of the setup script or as a dedicated one. Could you try this out? @ArtiomDivak 

The problem with only passing the version here is that it'll only work when run inside the GH CI.

File: tests/scripts/gather-code-coverage.sh [hunk 5]
```diff
@@ -7,6 +7,17 @@
...
+    exit 1
+fi
+
+# Construct the BUILD directory path using the extracted version
+BLUECHI_BUILD_DIR="/github/home/rpmbuild/BUILD/bluechi-${BLUECHI_VERSION}"
```
Comment (engelmi) [inline tests/scripts/gather-code-coverage.sh:11]: I think we could use the `$HOME` env var:
```suggestion
BLUECHI_BUILD_DIR="${HOME}/rpmbuild/BUILD/bluechi-${BLUECHI_VERSION}"
```
Not really sure this would work on local execution of the tests, but at least would be a bit more flexible.

File: tests/scripts/gather-code-coverage.sh (hunk 3 above)
Comment (ArtiomDivak) [reply tests/scripts/gather-code-coverage.sh]: This should have been deleted 
$BLUECHI_DEBUG_DIR is never used

File: tests/scripts/gather-code-coverage.sh (hunk 5 above)
Comment (ArtiomDivak) [reply tests/scripts/gather-code-coverage.sh:11]: ${HOME} in the CI is root

Comment (ArtiomDivak) [reply tests/scripts/gather-code-coverage.sh:11]: This is not supposed to be home /github/home is the dir that lcov ran in the other container

File: tests/scripts/gather-code-coverage.sh (hunk 3 above)
Comment (engelmi) [reply tests/scripts/gather-code-coverage.sh]: I see its removed :+1:

File: tests/scripts/gather-code-coverage.sh (hunk 5 above)
Comment (engelmi) [reply tests/scripts/gather-code-coverage.sh:11]: In which other container? So where is this coverage coming from? Its been a longer time since I had a look there, so not sure. Are those coverage files from the unit tests (created during build)?

Comment (ArtiomDivak) [reply tests/scripts/gather-code-coverage.sh:11]: You run the lcov on the CI. But when you run the integration test, some containers are coming up to run bluechi controller or bluechi agent, and at the end of their life, they gather the gcda file to copy it to the main machine (CI). You can see it in the machine.py file that runs the gather-code-coverage.py. I hope it is clear now.
The unit tests are run locally on the CI, so no need to work hard like with integration tests

**Review by engelmi — APPROVED** [review]
LGTM
