### PR TITLE
increase maximum line length of inih

### LINKED ISSUE #431: config: no error message if config file pass the max length in hirte manager
## Describe the bug

hirte should add a logic to not start and give an error (or at least a warning) message if the max length for the AllowedNodeName (**or any other option**) got achieved.

At this moment, if users are not aware of https://github.com/containers/hirte/blob/main/doc/docs/configuration.md#maximum-line-length it will **NOT** show any error on the hirte manager side just "anonymous node" tried to connect and in the node side "Unexpected node name". 

**Manager**
```
AllowedNodeNames=control,node1,qm.control123,node2,node3,node4,node5,node6,node7,node8,node9,node10,node11,node12,node13,node14,node15,node16,node17,node18,node19,node20,node21,node22,node23,node24,node25,node2
6

#  builddir/src/manager/hirte -c /etc/hirte/hirte.conf
2023-08-04 03:20:51,250+0000 DEBUG	: Final configuration used
2023-08-04 03:20:51,250+0000 INFO	: Starting hirte 0.5.0
2023-08-04 03:20:51,251+0000 DEBUG	: Connected to system bus
2023-08-04 03:20:54,795+0000 INFO	: Anonymous node disconnected
2023-08-04 03:20:57,045+0000 INFO	: Anonymous node disconnected
2023-08-04 03:20:59,295+0000 INFO	: Anonymous node disconnected
2023-08-04 03:20:59,733+0000 INFO	: Anonymous node disconnected
```

**Agent 1**:
```
NodeName=node25

# builddir/src/agent/hirte-agent -c /etc/hirte/agent.conf
ERROR	: Registering as 'node25' failed: Unexpected node name
```

Agent 02:
```
NodeName=control

# ./builddir/src/agent/hirte-agent -c /etc/hirte/hirte.conf
2023-08-04 03:22:30,444+0000 INFO	: Starting hirte-agent 0.5.0
2023-08-04 03:22:30,454+0000 INFO	: Connecting to manager on tcp:host=127.0.0.1,port=842
2023-08-04 03:22:30,455+0000 INFO	: Connected to manager as 'control'
```

If the user use the format below it start working:

```
AllowedNodeNames=control,
  node1,
  qm.control123,
  node2,
  node3,
  node4,
  node5,
  node6,
  node7,
  node8,
  node9,
  node10,
  node11,
  node12,
  node13,
  node14,
  node15,
  node16,
  node17,
  node18,
  node19,
  node20,
  node21,
  node22,
  node23,
  node24,
  node25,
  node26

Output from the node:
2023-08-04 03:23:35,718+0000 INFO	: Connected to manager as 'node25'
``` 

See Also: https://github.com/containers/hirte/pull/428

### PR DESCRIPTION
**Pull request by engelmi**
This PR fixes #431 by
- increasing the maximum line length used by the `inih` library (should've been added in #428, but missed it)
- providing an error message with the line number where the error occurred

### CODE REVIEW

File: src/libhirte/common/cfg.c [hunk 1]
```diff
@@ -132,16 +132,29 @@ int cfg_load_complete_configuration(
...
+                                "Error parsing configuration file '%s' on line %d\n",
+                                default_config_file,
+                                result);
+                        return -EINVAL;
                 }
         }
 
         if (custom_config_file != NULL) {
                 result = cfg_load_from_file(config, custom_config_file);
-                if (result < 0 && result != -ENOENT) {
```
Comment (engelmi) [inline src/libhirte/common/cfg.c:140]: Haven't had the case yet, but since we didn't handle `r > 0` (indicating parsing at line r failed) means we "skipped" an invalid configuration file.

**Review by mwperina — APPROVED** [review]
+1

File: meson.build [hunk 2]
```diff
@@ -27,10 +27,13 @@ if api_bus == 'user'
    common_cflags += '-DUSE_USER_API_BUS'
 endif
 
-# Set option of inih libraries maximum line length
+# inih library options
+# Set option of maximum line length
 # 500 characters for actual value
 # 20 characters as buffer (key, library internal usage, etc.)
 common_cflags += '-DINI_MAX_LINE=520'
```
Comment (dougsland) [inline meson.build:34]: Is it possible to increase to 1000 or 1500 instead of 500 ?

File: src/agent/agent.c [hunk 3]
```diff
@@ -551,12 +551,15 @@ bool agent_parse_config(Agent *agent, const char *configfile) {
...
                 result = cfg_load_from_file(agent->config, configfile);
-                if (result != 0) {
+                if (result < 0) {
                         fprintf(stderr,
                                 "Error loading configuration file '%s', error code '%s'.\n",
                                 configfile,
                                 strerror(-result));
                         return false;
+                } else if (result > 0) {
+                        fprintf(stderr, "Error parsing configuration file '%s' on line %d\n", configfile, result);
```
Comment (dougsland) [inline src/agent/agent.c:561]: Is it possible to check the length of the line?  Something like:
```
if (line_from_configuration contain length > MAX_LENGTH ) {  
      fprintf(stderr, "Achieved the max length in the configuration file, please see our man page for more information");
}
```

**Review by dougsland — CHANGES_REQUESTED** [review]
The patch works and it's nice but I have few comments.

File: meson.build (hunk 2 above)
Comment (engelmi) [reply meson.build:34]: Sure, 500 is just an arbitrary value like 1000 or 1500. It should be bigger than the max dns name length, though. Its just a memory size will definitely been allocated, so I'd not have it unreasonably large considering the multiline support.

File: src/agent/agent.c (hunk 3 above)
Comment (engelmi) [reply src/agent/agent.c:561]: No, unfortunately not. We just have the line number where some error has occurred.

File: meson.build (hunk 2 above)
Comment (dougsland) [reply meson.build:34]: right

File: src/agent/agent.c (hunk 3 above)
Comment (dougsland) [reply src/agent/agent.c:561]: all good, thanks for all your answers!

**Review by dougsland — APPROVED** [review]
