### PR TITLE
graceful node shutdown when manager destroyed

### LINKED ISSUE #578: valgrind error in integration test: Leak in manager_add_node (manager.c:256)
## Describe the bug

Integration test `fail /tests/tier0/monitor-agent-loses-connection` fails when run with valgrind, reporting the following error:

```
==49== Memcheck, a memory error detector
==49== Copyright (C) 2002-2022, and GNU GPL'd, by Julian Seward et al.
==49== Using Valgrind-3.21.0 and LibVEX; rerun with -h for copyright info
==49== Command: /usr/libexec/bluechi-agent
==49== Parent PID: 1
==49== 
==49== 
==49== HEAP SUMMARY:
==49==     in use at exit: 0 bytes in 0 blocks
==49==   total heap usage: 1,932 allocs, 1,932 frees, 307,834 bytes allocated
==49== 
==49== All heap blocks were freed -- no leaks are possible
==49== 
==49== For lists of detected and suppressed errors, rerun with: -s
==49== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
InlinedFun (node.c:132)
==44==    by 0x1133D6: manager_add_node (manager.c:256)
==44==    by 0x10D8ED: UnknownInlinedFun (manager.c:339)
==44==    by 0x10D8ED: main (main.c:88)
==44== 
==44== LEAK SUMMARY:
==44==    definitely lost: 128 bytes in 1 blocks
==44==    indirectly lost: 17,436 bytes in 191 blocks
==44==      possibly lost: 0 bytes in 0 blocks
==44==    still reachable: 0 bytes in 0 blocks
==44==         suppressed: 0 bytes in 0 blocks
==44== 
==44== For lists of detected and suppressed errors, rerun with: -s
==44== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
```

## To Reproduce

Please provide the steps to reproduce the issue.

1. Run integration tests with valgrind (after #575  merged)
2. See valgrind reports in the collected logs

### PR DESCRIPTION
**Pull request by mkemel**
Added graceful node_shutdown function that is called before node_unref, which goes over outstanding requests and cancels them.

This fixes a memory leak when bluechi-controller service is stopped via bluechi-controller itself

Fixes #578

### CODE REVIEW

File: src/manager/node.c [hunk 1]
```diff
@@ -206,6 +206,14 @@ void node_unref(Node *node) {
         free(node);
 }
 
+void node_shutdown(Node *node) {
```
Comment (engelmi) [inline src/manager/node.c:211]:
```suggestion
void node_cancel_outstanding_requests(Node *node) {
```
`shutdown` implies that it is doing a lot more, but its only canceling outstanding requests. Not sure if the proposed name is better, though.

File: src/manager/node.c [hunk 2]
```diff
@@ -1082,6 +1091,13 @@ static int agent_request_callback(sd_bus_message *m, void *userdata, UNUSED sd_b
         return req->cb(req, m, ret_error);
 }
 
+int agent_request_cancel(AgentRequest *r) {
+        _cleanup_agent_request_ AgentRequest *req = r;
```
Comment (engelmi) [inline src/manager/node.c:1103]: Just for confirmation: 
This `_cleanup_agent_request_` does an `agent_request_unref` and the implied `node_unref`, right?

File: src/manager/node.c [hunk 3]
```diff
@@ -1082,6 +1091,13 @@ static int agent_request_callback(sd_bus_message *m, void *userdata, UNUSED sd_b
...
+        req->is_cancelled = true;
+
+        return req->cb(req, NULL, NULL);
```
Comment (engelmi) [inline src/manager/node.c]: I am wondering if we can define a 
```C
typedef void (*agent_request_cancel_t)(void *userdata);
// ...
struct AgentRequest {
   // ...
   agent_request_cancel_t cancel;
```
similar to `agent_request_response_t` and pass it to `node_create_request`. Then we can do a 
```C
req->cancel(req->userdata); 
```

This would remove the cancel logic (which is just replying to the caller that the request got cancelled) from the callback logic received as a response from the agent. We'd need to provide two functions (for job_setup and plain sd bus messages), I think. 
What do you think?

File: src/manager/node.c (hunk 1 above)
Comment (mkemel) [reply src/manager/node.c:211]: This was the name suggested by @alexlarsson 
Also, cancelling these requests really serve the purpose of graceful shutdown, and that is what we really are doing here

File: src/manager/node.c (hunk 2 above)
Comment (mkemel) [reply src/manager/node.c:1103]: Yes, correct

File: src/manager/node.c (hunk 3 above)
Comment (mkemel) [reply src/manager/node.c]: I actually considered this option, but somehow it appeared to me that less complicated callback functions come at a price of more complicated AgentRequest structure and more complicated `node_create_request()` call. I think these are two equally valid implementations. @alexlarsson what do you think is better?

File: src/manager/node.c (hunk 1 above)
Comment (alexlarsson) [reply src/manager/node.c:211]: I think shutdown is a better word. Its about what the meaning of the operation is, i.e. "prepare for a shutdown", not about what it is currently doing, which is more of an internal thing.

Tomorrow we may notice that shutdown needs to do more things, then we just add it to shutdown().

Comment (alexlarsson) [reply src/manager/node.c:211]: Sometimes this operation is also called dispose, but I don't think the exact name is all that important. Its just a two phase object destruction.

File: src/manager/manager.c [hunk 4]
```diff
@@ -83,6 +83,7 @@ void manager_unref(Manager *manager) {
         Node *node = NULL;
         Node *next_node = NULL;
         LIST_FOREACH_SAFE(nodes, node, next_node, manager->nodes) {
+                node_shutdown(node);
                 node_unref(node);
         }
         LIST_FOREACH_SAFE(nodes, node, next_node, manager->anonymous_nodes) {
```
Comment (alexlarsson) [inline src/manager/manager.c:89]: Don't you also need to shutdown anonymous nodes?

File: src/manager/node.c [hunk 5]
```diff
@@ -1082,6 +1091,13 @@ static int agent_request_callback(sd_bus_message *m, void *userdata, UNUSED sd_b
         return req->cb(req, m, ret_error);
 }
 
+int agent_request_cancel(AgentRequest *r) {
+        _cleanup_agent_request_ AgentRequest *req = r;
+        req->is_cancelled = true;
+
```
Comment (alexlarsson) [inline src/manager/node.c:1107]: This worries me a bit. There is no fundamental guarantee that the unref() caused by this is the final unref of the request object, so there is no guarantee that the  sd_bus_slot_unrefp() in the finalizer is run, to technically you may still reach agent_request_callback, and then the callback would be run twice.

I think we should either force-unref the bus slot, or check is_cancelled in agent_request_callback.
I think the later is maybe simpler.

I mean, right now this is only called on program quit, so its not gonna cause issues, but that may change later.

File: src/manager/node.c (hunk 3 above)
Comment (alexlarsson) [reply src/manager/node.c]: I think this is overkill for the current requirements, and its more likely that someone forgets to implement the cancel request or gets it wrong, and then its not tested much.

File: src/manager/node.c (hunk 1 above)
Comment (engelmi) [reply src/manager/node.c:211]: Ah ok, I didn't know about the actual purpose of this function and assumed it based on the current implementation. That makes sense. 

When do we decide to move something to `node_shutdown`? For example, in `node_unref` we are also removing all proxy monitors. So couldn't we just define a weak dependency in the `AgentRequest` on the node (similar to the proxy) and take care of it in the unref?

File: src/manager/node.c (hunk 3 above)
Comment (alexlarsson) [inline src/manager/node.c]: I think you should pass an actual sd_bus_error (SD_BUS_ERROR_FAILED probably) here instead of NULL that says that the operation was cancelled.

Comment (engelmi) [reply src/manager/node.c]: Because the `node_create_request` would require the cancel to be specified, I think its more likely that the cancel check inside the callback gets forgotten (if there is one to be added). 
But I agree that its quite complicated to implement. So lets go with the current approach.

Comment (alexlarsson) [reply src/manager/node.c]: Ah, no the bus_error seems to be an out param, so you need to make a new error message with the error saying the operation was cancelled

File: src/manager/node.c [hunk 6]
```diff
@@ -1126,6 +1142,10 @@ AgentRequest *node_request_list_units(
 static int method_list_units_callback(AgentRequest *req, sd_bus_message *m, UNUSED sd_bus_error *ret_error) {
         sd_bus_message *request_message = req->userdata;
 
+        if (req->is_cancelled) {
```
Comment (alexlarsson) [inline src/manager/node.c]: None of these are necessary if you synthesize a message error in the cancel callback, the below sd_bus_message_is_method_error() call will be enough.

However, you might want node_method_list_units() and the other "start a request" methods to return directly if the node is shutdown, to avoid creating new request references.

File: src/manager/node.c (hunk 1 above)
Comment (alexlarsson) [reply src/manager/node.c:211]: Two way shutdown is a standard way to handle object finalization in C when there are risks for reference cycles.

Basically, "unref" of an object means "i don't personally need this anymore". But sometimes you want something more final than that, more like "this object should never be used anymore". In the later case you can't just jank it away from other owners of refs, as those would then reference freed memory, so instead you introduce a new state where something is "shut down, but memory is still valid". Such objects should not allow new operations on the, and all internal outstanding references should be broken to avoid any problems with circular dependencies.

In this particular case we need to shutdown the node, because we're exiting the app, and there may be references to the request objects that are external to the app (i.e. outstanding dbus calls) that make the agent requests not be cleanly freed.

But yes, you're right, one approach for ownership is to use weak references, which in this case would mean make the AgentRequests not reference the Node and have the Node finalizer just unref outstanding requests. In practice, this will work in current bluechi, because we will only do the final unref of the node when exiting the program. But, as a general principle, if someone calls an async operation like node_method_list_units() that expresses an interest in the result, and you want a callback eventually, even if you don't necessarily need to keep the node object reference around. This won't happen if the request doesn't ref the node.

File: src/manager/manager.c (hunk 4 above)
Comment (mkemel) [reply src/manager/manager.c:89]: I thought we can't send requests to anonymous nodes anyway, so there is no need to do that.
On the other hand maybe they'll need some other handling in the future, so it makes sense to call shutdown for them as well

File: src/manager/node.c (hunk 5 above)
Comment (mkemel) [reply src/manager/node.c:1107]: Good point, done that

File: src/manager/node.c (hunk 3 above)
Comment (mkemel) [reply src/manager/node.c]: Done

File: src/manager/node.c (hunk 6 above)
Comment (mkemel) [reply src/manager/node.c]: Done

**Comment by alexlarsson** [comment]
lgtm

**Review by alexlarsson — APPROVED** [review]
