### PR TITLE
test: add getaddress mock

### LINKED ISSUE #398: Remove network dependency in get_address_test
## Describe the bug

`get_address` internally uses of `getaddrinfo` to get hints to use either IPv4 or IPv6. While this is fine to use in production, its not a good practice to use in tests since it might fail due to "outside" conditions. For example, if there is no dns resolution, the `get_address_test` fails due to a timeout as can be seen in the following output: 

```bash
get_address_test time out (After 30 seconds)
11/11 get_address_test     TIMEOUT        30.04s   killed by signal 15 SIGTERM
>>> MALLOC_PERTURB_=154 /builddir/build/BUILD/hirte-0.4.0/redhat-linux-build/src/libhirte/test/common/network/get_address_test
Summary of Failures:
11/11 get_address_test     TIMEOUT        30.04s   killed by signal 15 SIGTERM
```

## To Reproduce

Running `meson test -C builddir` with no dns resolution active on the machine. 

## Expected behavior

Either a passing or disabled `get_address_test`. 

## Proposal to fix

Create a type that is matching the `getaddrinfo` and having it being passed in as function pointer. This way the caller can determine the behavior of the function. For the production code, just pass the original `getaddrinfo`. For the test code, just implement a dummy function that sets the `res->ai_family` and `res->ai_addr` and pass it to the call. 
If that is not possible or too complicated, lets deactivate the test for now (removing from the list in meson.build).

### PR DESCRIPTION
**Pull request by dougsland**
There are test pipelines environments that cannot use external network due security restrictions. This patch ensure the code can be still tested.

Fixes: https://github.com/containers/bluechi/issues/398

Signed-off-by: Douglas Schilling Landgraf <dougsland@redhat.com>
Signed-off-by: Michael Engel <mengel@redhat.com>

### CODE REVIEW

**Comment by dougsland** [comment]
A new PR on top of renamed repo. ;-)

**Comment by rhatdan** [comment]
LGTM

File: src/libhirte/common/network.h [hunk 1]
```diff
@@ -16,10 +16,12 @@ bool is_ipv4(const char *domain);
...
 char *get_hostname();
-int get_address(const char *domain, char **ip_address);
 
 char *typesafe_inet_ntop4(const struct sockaddr_in *addr);
 char *typesafe_inet_ntop6(const struct sockaddr_in6 *addr);
 
 char *assemble_tcp_address(const struct sockaddr_in *addr);
 char *assemble_tcp_address_v6(const struct sockaddr_in6 *addr);
+
+typedef int (*getaddrinfo_func)(const char *, const char *, const struct addrinfo *, struct addrinfo **);
```
Comment (engelmi) [inline src/libhirte/common/network.h]: Could you add names for the parameters so its easier to tell what each single parameter is for?

File: src/libhirte/test/common/network/get_address_test.c [hunk 2]
```diff
@@ -7,88 +7,102 @@
...
-/* test case for actually resolving a domain to an IP */
-bool test_get_address_localhost() {
-        const char *domain = "localhost";
-        int expected_ret = 0;
-        const char *expected_addressv4 = "127.0.0.1";
-        const char *expected_addressv6 = "::1";
+        return current_test_case.expected_result;
+}
 
+/* test cases where domain already contains an IPv4 or IPv6 */
```
Comment (engelmi) [inline src/libhirte/test/common/network/get_address_test.c]: This inline comment can be removed.

File: src/libhirte/test/common/network/get_address_test.c [hunk 3]
```diff
@@ -7,88 +7,102 @@
...
         }
-        if (ip != NULL) {
-                fprintf(stdout, "FAILED: get_address('%s') - Expected null, but got non-null (%s)\n", domain, ip);
-                return false;
+
+        /*
+         * To emulate what getaddrinfo does, allocate both sockaddr_in and
+         * addrinfo together so freeaddrinfo() will free the entire thing.
+         */
+        *pai = malloc0(sizeof(struct addrinfo) + sizeof(struct sockaddr_in6));
```
Comment (engelmi) [inline src/libhirte/test/common/network/get_address_test.c:47]: This doesn't make sense. `freeaddrinfo` will probably call `free` on the `pai` pointer, so all memory is freed - including the subsequently set `sockaddr_in`. The subsequent approach with the `offset` works because of that - using the allocated memory here - and simply calling `free` on the `pai` pointer in the get_address code would probably suffice.

**Comment by dougsland** [comment]
Just for reference:  Speaking with Michael, he raised that we are using different gcc versions which explain why I see some additional warnings and build-base not.

- `build-base` uses gcc 11.4.1

Locally I am using Fedora 38:
```
# cat /etc/redhat-release
Fedora release 38 (Thirty Eight)

# gcc -v
gcc version 13.2.1 20230728 (Red Hat 13.2.1-1) (GCC)
```

See-also: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=106393

**Review by engelmi — APPROVED** [review]
LGTM

**Comment by dougsland** [comment]
Let's see if brew will fly
