### PR TITLE
fix issues detected by gcc -fanalyzer option

### LINKED ISSUE #604: Add gcc option `-fanalyzer`
## Please describe what you would like to see

In order to ensure a high code quality, it would be great to enable the [-fanalyzer](https://gcc.gnu.org/onlinedocs/gcc-10.1.0/gcc/Static-Analyzer-Options.html) option of `gcc`. This way we are able to find more potential leaks (e.g. a fd leak: https://github.com/containers/bluechi/pull/602). 

This can easily be enabled in meson by adding:
```bash
add_project_arguments('-fanalyzer', language: 'c')
```

However, the currently existing issues detected by this need to be tackled first so that the CI isn't blocked. 

__Note:__ Apparently, different `gcc` versions enable different warnings (comparing [gcc 10.1.0](https://gcc.gnu.org/onlinedocs/gcc-10.1.0/gcc/Static-Analyzer-Options.html) and [gcc 13.2.0](https://gcc.gnu.org/onlinedocs/gcc-13.2.0/gcc/Static-Analyzer-Options.html)). Therefore, it is advisable to use the `gcc` version thats installed in the build container of BlueChi.

### PR DESCRIPTION
**Pull request by engelmi**
Fixes: https://github.com/containers/bluechi/issues/604

Fixed detected issues or suppressed warnings for false-positives that couldn't be fixed. Also sets the with_analyzer meson option to true as default.

### CODE REVIEW

File: src/client/method_monitor.c [hunk 1]
```diff
@@ -325,7 +325,13 @@ static Node *
                          const char *node_state,
                          uint64_t last_seen_timestamp) {
         Node *node = malloc0(sizeof(Node));
+        if (node == NULL) {
+                return NULL;
+        }
         node->connection = malloc0(sizeof(NodeConnection));
+        if (node->connection == NULL) {
+                return NULL;
```
Comment (mwperina) [inline src/client/method_monitor.c:335]: Shouldn't you deallocate the `node` object before leaving?

Comment (engelmi) [reply src/client/method_monitor.c:335]: Yes, good point. Updated it. Could you have another look? @mwperina

**Review by mwperina — APPROVED** [review]
LGTM

File: meson.build [hunk 2]
```diff
@@ -29,6 +29,7 @@ endif
 
 if get_option('with_analyzer')
   add_project_arguments('-fanalyzer', language : 'c')
+  add_project_arguments('-Wno-analyzer-malloc-leak', language : 'c')
```
Comment (engelmi) [inline meson.build:32]: `-fanalyzer` finds a few possible malloc leaks. They are quite complex to track down/understand and need verification that they are actually leaks or maybe false-positives. Because of that I turned this option off for now and tackle the malloc leaks in dedicated issues. This way we already have the static analysis in the CI and prevent other issues. 

I create the additional issues as soon as this PR is merged.

**Comment by engelmi** [comment]
@mwperina Could you have another look? I changed quite a bit. 
/cc @ericcurtin If you have time, I'd appreciate your review.

File: build-scripts/clang-tidy-all.sh [hunk 3]
```diff
@@ -24,5 +24,5 @@ do
         -I $BUILD_DIR \
         -I $SUBPROJECTS_DIR/hashmap.c \
         -I $SUBPROJECTS_DIR/inih \
-        -include config.h
+        -include config.h -Wno-unknown-warning-option
```
Comment (mwperina) [inline build-scripts/clang-tidy-all.sh]: One option per line please:

```
        -I $SUBPROJECTS_DIR/inih \
        -Wno-unknown-warning-option \
        -include config.h 
```

File: src/libbluechi/test/common/network/assemble_tcp_address.c [hunk 4]
```diff
@@ -69,7 +69,8 @@ bool test_assemble_tcp_address_v6(const struct sockaddr_in6 *input, const char *
 
 bool test_assemble_tcp_address(const struct sockaddr_in *input, const char *expectedResult) {
         _cleanup_free_ char *result = assemble_tcp_address(input);
-        if ((result == NULL && expectedResult != NULL) || (result != NULL && !streq(result, expectedResult))) {
+        if ((result == NULL && expectedResult != NULL) || (result != NULL && expectedResult == NULL) ||
+            (result != NULL && !streq(result, expectedResult))) {
```
Comment (mwperina) [inline src/libbluechi/test/common/network/assemble_tcp_address.c:73]: Wouldn't having one condition block per line make the code more readable?

```
        if ((result == NULL && expectedResult != NULL) || 
            (result != NULL && expectedResult == NULL) ||
            (result != NULL && !streq(result, expectedResult))) {
```

**Review by ericcurtin — APPROVED** [review]
LGTM

If this means -fanalyzer on by default:

```
option('with_analyzer', type : 'boolean', value : 'true',
    description : 'Add the gcc option -fanalyzer for static analysis')
```

that's ok, it could be a good thing, so people have checked by the static analyzer before they even push and go though CI...

But... People will likely build this with many different versions of gcc, etc. so they will get a variation of results...

To be honest if it was me, I would default it to off and just explicitly turn it on in CI for one specific platform (latest version of Fedora probably makes most sense, because -fanalyzer is a newish tool, the latest version is probably in better shape). Then they would see the red X reported on the MR. Because otherwise I think on many local developer machines this will break the build because it's common for people to run all sorts of versions of tools and distros! And I think it would be cool if bluechi was adopted by all sorts of Linux distros.

I tried this also, because I was sure that this meant it would break clang builds by default:

```
export CC=clang
export CXX=clang++
meson setup builddir
meson compile -C builddir
```

But in fact, clang builds are already broken prior to this PR.

I'm happy to fix clang support in a follow on PR though.

clang compiler support is worth keeping around, that could also be something worth adding to CI, it's useful and some Linux distros build with that alternatively.

But happy to go with whatever you think!

**Comment by ericcurtin** [comment]
@davidmalcolm you seem to be the leading -fanalyzer expert from my reading :sweat_smile: 

How achievable is it to maintain a "-fanalyzer" on by default C codebase?

File: build-scripts/clang-tidy-all.sh (hunk 3 above)
Comment (engelmi) [reply build-scripts/clang-tidy-all.sh]: Good point, changed.

File: src/libbluechi/test/common/network/assemble_tcp_address.c (hunk 4 above)
Comment (engelmi) [reply src/libbluechi/test/common/network/assemble_tcp_address.c:73]: I agree that the suggested formatting would be more readable, but, unfortunately, the formatting is enforced like this. 
In order to change this, I'd need to figure out which options for clang-format to adjust and then this would probably entail diff in unrelated code parts.

**Comment by engelmi** [comment]
Thanks for your review @ericcurtin 

> Because otherwise I think on many local developer machines this will break the build because it's common for people to run all sorts of versions of tools and distros!

I agree that enabling it by default might lead to more problems for developers using all sorts of tools and versions. I switched the default to `false` again and enabled it only in the CI when building and running unit tests ~as well as in the RPM spec~. So the CI with the [build-base](https://quay.io/repository/bluechi/build-base) is the "source of truth" in terms of tools, versions, etc. 

To avoid a CI ping pong trying to fix the detected issues from the static code analysis, I added a small section in the developer readme on how to debug and fix these issues locally in the container used by CI.

~Since the RPM build seems to be more strict and setting additional compiler flags, I added a small section in the developer readme on how to build the RPM in the build-base container used in the CI - this way its possible to debug and fix the issues locally and doesn't requires CI ping pong.~ 

> I'm happy to fix clang support in a follow on PR though.

Our focused compiler is gcc, but if clang support doesn't require huge code changes, I think that would be great :)

File: .github/workflows/unit-tests.yml [hunk 5]
```diff
@@ -23,6 +23,7 @@ jobs:
         run: |
           meson setup builddir
           meson configure -Db_coverage=true builddir
+          meson configure -Dwith_analyzer=true builddir
```
Comment (mwperina) [inline .github/workflows/unit-tests.yml]: Why are we configuring twice? Wouldn't it be better to configure only once with all options?

```
  meson configure \
      -Dwith_analyzer=true \
      -Dwith_coverage=true \
      builddir
```

File: build-scripts/clang-tidy-all.sh [hunk 6]
```diff
@@ -24,5 +24,6 @@ do
         -I $BUILD_DIR \
         -I $SUBPROJECTS_DIR/hashmap.c \
         -I $SUBPROJECTS_DIR/inih \
-        -include config.h
+        -include config.h \
+        -Wno-unknown-warning-option
```
Comment (mwperina) [inline build-scripts/clang-tidy-all.sh]: I'd leave the `config.h` line last, it will probably never change, so we don't need to handle `\` with the last line. And all other options could be mentioned before `config.h`:

```
        -I $SUBPROJECTS_DIR/inih \
        -Wno-unknown-warning-option \
        -include config.h
```

File: src/libbluechi/test/common/network/assemble_tcp_address.c (hunk 4 above)
Comment (mwperina) [reply src/libbluechi/test/common/network/assemble_tcp_address.c:73]: OK, so let's leave as is for now

**Review by ericcurtin — APPROVED** [review]

File: .github/workflows/unit-tests.yml (hunk 5 above)
Comment (engelmi) [reply .github/workflows/unit-tests.yml]: Changed.

File: build-scripts/clang-tidy-all.sh (hunk 6 above)
Comment (engelmi) [reply build-scripts/clang-tidy-all.sh]: Since `-I` is including directories and `-include` a file I think they semantically similar and should be next to each other. But I am fine with changing it.

**Comment by davidmalcolm** [comment]
> @davidmalcolm you seem to be the leading -fanalyzer expert from my reading 😅

Hi!  I'm the upstream author and maintainer of -fanalyzer.

> 
> How achievable is it to maintain a "-fanalyzer" on by default C codebase?

Note that "-fanalyzer" is neither sound not complete: expect there to be both false positives and false negatives.

Maybe pick a subset of warnings that have a good signal:noise ratio, and enable just those?

Also, the answer to your question may depend on GCC version.  The analyzer is moving much faster than the rest of GCC's code.  I originally added the analyzer to GCC in GCC 10, but the initial implementation had at least two major design errors - don't expect GCC 10's -fanalyzer to be usable.  I've been overhauling the internals, fixing issues release by release, and we're adding new warnings to it, so if you're looking to default to it "on", then you should specify a particular minimum GCC release for that.

Hope this is constructive, and that the analyzer is useful.

**Comment by ericcurtin** [comment]
I wrote this codebase from the start with it on and it builds clean with it on:

https://github.com/containers/initoverlayfs

I've also been running it here, but have failed to tease out everything:

https://github.com/inotify-tools/inotify-tools

I've found when it's on from the start of a project, it's manageable to keep it building with -fanalyzer on.

Existing codebases are harder to build completely green with -fanalyzer on because it's just a lot of work to help -fanalyzer understand every line of code when the code is already written with lots of dependancies. That's why I like how @engelmi didn't get too pedantic about fixing every little thing here :)

Thanks for your work @davidmalcolm it's my favorite static analyzer tool these days, seems to have less false positives than others I've used.

File: build-scripts/clang-tidy-all.sh (hunk 6 above)
Comment (mwperina) [reply build-scripts/clang-tidy-all.sh]: Hmm, that's something I didn't realize, sorry.  In that case you are right, have together `-I` and `-included` makes sense. So up to you if you want to do another change or merge as is

**Comment by engelmi** [comment]
> Note that "-fanalyzer" is neither sound not complete: expect there to be both false positives and false negatives.

Hopefully, by combining `-fanalyzer` for static code analysis in combination with runtime analysis (e.g. via `valgrind`) we can improve (and keep) the code quality high over the long term. I think both tools complement each other really well. 

> Maybe pick a subset of warnings that have a good signal:noise ratio, and enable just those?

Yes, I agree. Currently, I only had to disable the `malloc leak` (for now). 

> Also, the answer to your question may depend on GCC version. The analyzer is moving much faster than the rest of GCC's code. I originally added the analyzer to GCC in GCC 10, but the initial implementation had at least two major design errors - don't expect GCC 10's -fanalyzer to be usable. I've been overhauling the internals, fixing issues release by release, and we're adding new warnings to it, so if you're looking to default to it "on", then you should specify a particular minimum GCC release for that.

I think currently we are using GCC 11.4 in the CI and builds. So our minimum GCC release is determined by that. Its probably still hard to turn it on by default for BlueChi since we built also for a lot of other platforms/archs where different issues are found (e.g. in one of the [latest copr builds](https://copr.fedorainfracloud.org/coprs/g/centos-automotive-sig/bluechi-snapshot/build/6567731/)). So even though I'd want to fix every issue it finds, we have to be pragmatic.  

> Hope this is constructive, and that the analyzer is useful.

Definitely! Its great to your perspective on the matter and thank you for work! @davidmalcolm
