### PR TITLE
Make Agent Register request asynchronous

### LINKED ISSUE #950: Failed to call SwitchController DBus method to bluechi-agent
## Describe the bug

I have an issue where calling SwitchController DBus method on bluechi-agent fails with a timeout when bluechi-agent never connected to bluechi-controller. However, if bluechi-agent has ever connected to bluechi-controller and retries to connect to bluechi-controller, calling SwitchController DBus method on bluechi-agent succeeds.

## To Reproduce

Prerequisite
- host 192.168.16.101 exists on local network and is running bluechi-controller. 
- host 192.168.16.111 does not exist on local network.

Failure case
1. start bluechi-agent with host 192.168.16.111
```
root@42dot-ak7:~# cat /etc/bluechi/agent.conf 
[bluechi-agent]
NodeName=ak7_master_main
ControllerHost=192.168.16.111
HeartbeatInterval=2000
```

```
root@42dot-ak7:~# systemctl start bluechi-agent
```

```
root@42dot-ak7:~# journalctl -f -u bluechi-agent
Sep 20 15:02:53 42dot-ak7 systemd[1]: Started BlueChi systemd service controller agent daemon.
Sep 20 15:02:53 42dot-ak7 bluechi-agent[3062]: Starting bluechi-agent 0.8.0-1
Sep 20 15:02:53 42dot-ak7 bluechi-agent[3062]: Connecting to controller on tcp:host=192.168.16.111,port=842
Sep 20 15:02:56 42dot-ak7 bluechi-agent[3062]: Registering as 'ak7_master_main' failed: Transport endpoint is not connected
Sep 20 15:02:56 42dot-ak7 bluechi-agent[3062]: Initial controller connection failed, retrying
Sep 20 15:02:56 42dot-ak7 bluechi-agent[3062]: Trying to connect to controller (try 1)
Sep 20 15:02:56 42dot-ak7 bluechi-agent[3062]: Connecting to controller on tcp:host=192.168.16.111,port=842
Sep 20 15:02:59 42dot-ak7 bluechi-agent[3062]: Registering as 'ak7_master_main' failed: Transport endpoint is not connected
Sep 20 15:02:59 42dot-ak7 bluechi-agent[3062]: Trying to connect to controller (try 2)
Sep 20 15:02:59 42dot-ak7 bluechi-agent[3062]: Connecting to controller on tcp:host=192.168.16.111,port=842
Sep 20 15:03:02 42dot-ak7 bluechi-agent[3062]: Registering as 'ak7_master_main' failed: Transport endpoint is not connected
Sep 20 15:03:02 42dot-ak7 bluechi-agent[3062]: Trying to connect to controller (try 3)
Sep 20 15:03:02 42dot-ak7 bluechi-agent[3062]: Connecting to controller on tcp:host=192.168.16.111,port=842
Sep 20 15:03:05 42dot-ak7 bluechi-agent[3062]: Registering as 'ak7_master_main' failed: Transport endpoint is not connected
...
```

2. call SwitchController DBus method with host 192.168.16.101
```
root@42dot-ak7:~# dbus-send --system --dest=org.eclipse.bluechi.Agent --print-reply --type=method_call /org/eclipse/bluechi org.eclipse.bluechi.Agent.SwitchController string:'tcp:host=192.168.16.101,port=842'
Error org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
```

3. `busctl introspect` command also is failed
```
root@42dot-ak7:~# busctl introspect org.eclipse.bluechi.Agent /org/eclipse/bluechi
Failed to introspect object /org/eclipse/bluechi of service org.eclipse.bluechi.Agent: Connection timed out
```

Success case
1. start bluechi-agent with host 192.168.16.101
2. call SwitchController DBus method with host 192.168.16.111
3. call SwitchController DBus method with host 192.168.16.101
```
root@42dot-ak7:~# cat /etc/bluechi/agent.conf 
[bluechi-agent]
NodeName=ak7_master_main
ControllerHost=192.168.16.101
HeartbeatInterval=2000
```

```
root@42dot-ak7:~# systemctl start bluechi-agent
root@42dot-ak7:~#
root@42dot-ak7:~# dbus-send --system --dest=org.eclipse.bluechi.Agent --print-reply --type=method_call /org/eclipse/bluechi org.eclipse.bluechi.Agent.SwitchController string:'tcp:host=192.168.16.111,port=842'
method return time=1726812297.956766 sender=:1.38 -> destination=:1.40 serial=9 reply_serial=2
root@42dot-ak7:~#
root@42dot-ak7:~# dbus-send --system --dest=org.eclipse.bluechi.Agent --print-reply --type=method_call /org/eclipse/bluechi org.eclipse.bluechi.Agent.SwitchController string:'tcp:host=192.168.16.101,port=842'
method return time=1726812313.323543 sender=:1.38 -> destination=:1.41 serial=14 reply_serial=2
```

```
root@42dot-ak7:~# journalctl -f -u bluechi-agent
Sep 20 15:04:34 42dot-ak7 systemd[1]: Started BlueChi systemd service controller agent daemon.
Sep 20 15:04:34 42dot-ak7 bluechi-agent[3347]: Starting bluechi-agent 0.8.0-1
Sep 20 15:04:34 42dot-ak7 bluechi-agent[3347]: Connecting to controller on tcp:host=192.168.16.101,port=842
Sep 20 15:04:34 42dot-ak7 bluechi-agent[3347]: Connected to controller as 'ak7_master_main'
Sep 20 15:04:54 42dot-ak7 bluechi-agent[3347]: CONTROLLER ADDRESS changed to tcp:host=192.168.16.111,port=842
Sep 20 15:04:54 42dot-ak7 bluechi-agent[3347]: Disconnected from controller
Sep 20 15:04:54 42dot-ak7 bluechi-agent[3347]: Connecting to controller on tcp:host=192.168.16.111,port=842
Sep 20 15:04:57 42dot-ak7 bluechi-agent[3347]: Registering as 'ak7_master_main' failed: Transport endpoint is not connected
Sep 20 15:04:57 42dot-ak7 bluechi-agent[3347]: Trying to connect to controller (try 1)
Sep 20 15:04:57 42dot-ak7 bluechi-agent[3347]: Connecting to controller on tcp:host=192.168.16.111,port=842
Sep 20 15:05:01 42dot-ak7 bluechi-agent[3347]: Registering as 'ak7_master_main' failed: Transport endpoint is not connected
Sep 20 15:05:01 42dot-ak7 bluechi-agent[3347]: Trying to connect to controller (try 2)
Sep 20 15:05:01 42dot-ak7 bluechi-agent[3347]: Connecting to controller on tcp:host=192.168.16.111,port=842
Sep 20 15:05:04 42dot-ak7 bluechi-agent[3347]: Registering as 'ak7_master_main' failed: Transport endpoint is not connected
Sep 20 15:05:04 42dot-ak7 bluechi-agent[3347]: Trying to connect to controller (try 3)
Sep 20 15:05:04 42dot-ak7 bluechi-agent[3347]: Connecting to controller on tcp:host=192.168.16.111,port=842
Sep 20 15:05:07 42dot-ak7 bluechi-agent[3347]: Registering as 'ak7_master_main' failed: Transport endpoint is not connected
Sep 20 15:05:07 42dot-ak7 bluechi-agent[3347]: Trying to connect to controller (try 4)
Sep 20 15:05:07 42dot-ak7 bluechi-agent[3347]: Connecting to controller on tcp:host=192.168.16.111,port=842
Sep 20 15:05:10 42dot-ak7 bluechi-agent[3347]: Registering as 'ak7_master_main' failed: Transport endpoint is not connected
Sep 20 15:05:10 42dot-ak7 bluechi-agent[3347]: Trying to connect to controller (try 5)
Sep 20 15:05:10 42dot-ak7 bluechi-agent[3347]: Connecting to controller on tcp:host=192.168.16.111,port=842
Sep 20 15:05:13 42dot-ak7 bluechi-agent[3347]: Registering as 'ak7_master_main' failed: Transport endpoint is not connected
Sep 20 15:05:13 42dot-ak7 bluechi-agent[3347]: CONTROLLER ADDRESS changed to tcp:host=192.168.16.101,port=842
Sep 20 15:05:13 42dot-ak7 bluechi-agent[3347]: Disconnected from controller
Sep 20 15:05:13 42dot-ak7 bluechi-agent[3347]: Connecting to controller on tcp:host=192.168.16.101,port=842
Sep 20 15:05:13 42dot-ak7 bluechi-agent[3347]: Connected to controller as 'ak7_master_main'
```

## Expected behavior
When bluechi-agent never connected to bluechi-controller, if call SwitchController DBus method with host 192.168.16.101, bluechi-agent must connect to bluechi-controller of host 192.168.16.101.

```
root@42dot-ak7:~# dbus-send --system --dest=org.eclipse.bluechi.Agent --print-reply --type=method_call /org/eclipse/bluechi org.eclipse.bluechi.Agent.SwitchController string:'tcp:host=192.168.16.101,port=842'
method return time=1726812313.323543 sender=:1.38 -> destination=:1.41 serial=14 reply_serial=2
```

```
root@42dot-ak7:~# journalctl -f -u bluechi-agent
...
Sep 20 15:05:10 42dot-ak7 bluechi-agent[3347]: Trying to connect to controller (try 5)
Sep 20 15:05:10 42dot-ak7 bluechi-agent[3347]: Connecting to controller on tcp:host=192.168.16.111,port=842
Sep 20 15:05:13 42dot-ak7 bluechi-agent[3347]: Registering as 'ak7_master_main' failed: Transport endpoint is not connected
Sep 20 15:05:13 42dot-ak7 bluechi-agent[3347]: CONTROLLER ADDRESS changed to tcp:host=192.168.16.101,port=842
Sep 20 15:05:13 42dot-ak7 bluechi-agent[3347]: Disconnected from controller
Sep 20 15:05:13 42dot-ak7 bluechi-agent[3347]: Connecting to controller on tcp:host=192.168.16.101,port=842
Sep 20 15:05:13 42dot-ak7 bluechi-agent[3347]: Connected to controller as 'ak7_master_main'
```

### LINKED ISSUE #966: Failed to trigger SwitchController DBus method when bluechi-agent tries reconnecting to bluechi-controller
## Describe the bug

I have an issue where calling SwitchController DBus method on bluechi-agent fails with a timeout when bluechi-agent tries reconnecting to bluechi-controller after bluechi-agent disconnects to bluechi-controller by network disconnection of node that bluechi-controller is running.

## To Reproduce
There are two host 192.168.16.101, 192.168.16.102 that are running bluechi-controller.
There is a host 192.168.16.103 that is running bluechi-agent.
Three hosts are connected to the same local network.

1. Start bluechi-agent on host 192.168.16.103 and the bluechi-agent connected to bluechi-controller of host 192.168.16.101
```
Oct 24 14:55:47 42dot-ak7 bluechi-agent[636331]: Connecting to controller on tcp:host=192.168.16.101,port=842
Oct 24 14:55:47 42dot-ak7 bluechi-agent[636331]: Connected to controller as 'ak7_master_main'
```

2. Unplug network cable of  host 192.168.16.101, then bluechi-agent disconnects to bluechi-controller of  host 192.168.16.101
```
Oct 24 14:56:51 42dot-ak7 bluechi-agent[636331]: Did not receive heartbeat from controller since '2500'ms. Disconnecting it...
Oct 24 14:56:51 42dot-ak7 bluechi-agent[636331]: Disconnected from controller
Oct 24 14:56:51 42dot-ak7 bluechi-agent[636331]: Connecting to controller on tcp:host=192.168.16.101,port=842
Oct 24 14:57:56 42dot-ak7 bluechi-agent[636331]: Registering as 'ak7_master_main' failed: Transport endpoint is not connected
Oct 24 14:57:56 42dot-ak7 bluechi-agent[636331]: Trying to connect to controller (try 1)
Oct 24 14:57:56 42dot-ak7 bluechi-agent[636331]: Connecting to controller on tcp:host=192.168.16.101,port=842
Oct 24 14:57:59 42dot-ak7 bluechi-agent[636331]: Registering as 'ak7_master_main' failed: Transport endpoint is not connected
Oct 24 14:57:59 42dot-ak7 bluechi-agent[636331]: Trying to connect to controller (try 2)
Oct 24 14:57:59 42dot-ak7 bluechi-agent[636331]: Connecting to controller on tcp:host=192.168.16.101,port=842
Oct 24 14:58:02 42dot-ak7 bluechi-agent[636331]: Registering as 'ak7_master_main' failed: Transport endpoint is not connected
...
```

3. Trigger the SwitchController on host 192.168.16.103 to switch controller to 192.168.16.102 before the first "Registering as 'ak7_master_main' failed: Transport endpoint is not connected" message appears in, then i get an error with timeout.
```
root@42dot-ak7:~# dbus-send --system --dest=org.eclipse.bluechi.Agent --print-reply --type=method_call /org/eclipse/bluechi org.eclipse.bluechi.Agent.SwitchController string:'tcp:host=192.168.16.102,port=842'
Error org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
```

## Expected behavior

Under the above conditions, if we trigger SwitchController on host 192.168.16.103 to switch the controller to 192.168.16.102, the SwitchController trigger should succeed.

```
root@42dot-ak7:~# dbus-send --system --dest=org.eclipse.bluechi.Agent --print-reply --type=method_call /org/eclipse/bluechi org.eclipse.bluechi.Agent.SwitchController string:'tcp:host=192.168.16.102,port=842'
method return time=1729749456.721574 sender=:1.899 -> destination=:1.1191 serial=338 reply_serial=2
```

### PR DESCRIPTION
**Pull request by mkemel**
The "Register" agent->controller method call could get stuck when the IP address configured as ControllerHost does not exist. This timeout of about 2 seconds could completely occupy the event loop and would not allow other calls on the DBus API of the Agent.

Making the "Register" method call asynchronous we allow the event loop to stay unoccupied and be able to accept SwitchController request.

Resolves: #950 
Resolves: #966

### CODE REVIEW

**Comment by mkemel** [comment]
Ready for review. 
I think if everything's fine this can be merged, and I will add an integration test for that after the shutdown.

GH Integration tests failing at the prepare stage currently, probably infra issue

**Review by ArtiomDivak — APPROVED** [review]
LGTM

File: src/agent/agent.c [hunk 1]
```diff
@@ -2791,6 +2769,73 @@ static bool agent_connect(Agent *agent) {
...
+                        INTERNAL_AGENT_INTERFACE,
+                        internal_agent_vtable,
+                        agent);
+        if (r < 0) {
+                bc_log_errorf("Failed to add agent vtable: %s", strerror(-r));
+                return false;
+        }
+
+        _cleanup_sd_bus_message_ sd_bus_message *bus_msg = NULL;
+        sd_bus_error error = SD_BUS_ERROR_NULL;
```
Comment (ArtiomDivak) [inline src/agent/agent.c]: Maybe change too `_cleanup_sd_bus_error_ sd_bus_error error = SD_BUS_ERROR_NULL;`

Comment (mkemel) [reply src/agent/agent.c]: If there is an error it is freed manually further, this was copied from the old code, but actually it is not needed anymore

Comment (mkemel) [reply src/agent/agent.c]: Good catch @ArtiomDivak 
Fixed

**Comment by mkemel** [comment]
Moved the PR back to draft, found a memory issue
Will handle after shutdown

File: src/agent/agent.c [hunk 2]
```diff
@@ -169,6 +169,14 @@ static int agent_heartbeat_timer_callback(sd_event_source *event_source, UNUSED
         Agent *agent = (Agent *) userdata;
 
         int r = 0;
+        if (agent->connection_state == AGENT_CONNECTION_STATE_CONNECTING) {
```
Comment (engelmi) [inline src/agent/agent.c:176]: Maybe adding an inline-comment like this helps making clear what we are doing:
```C
/* Being in connecting state when the timer callback is executed implies that 
 * the agent hasn't received a reply from the controller yet. In this case, the  
 * previous register callback is dropped and the agent is set into a retrying state.
 */
```

File: src/agent/agent.c [hunk 3]
```diff
@@ -532,6 +540,9 @@ void agent_unref(Agent *agent) {
                 sd_event_unrefp(&agent->event);
         }
 
+        if (agent->register_call_slot != NULL) {
+                sd_bus_slot_unrefp(&agent->register_call_slot);
```
Comment (engelmi) [inline src/agent/agent.c:548]:
```suggestion
                sd_bus_slot_unrefp(&agent->register_call_slot);
                agent->register_call_slot = NULL;
```

File: src/agent/agent.c [hunk 4]
```diff
@@ -532,6 +540,9 @@ void agent_unref(Agent *agent) {
                 sd_event_unrefp(&agent->event);
         }
 
+        if (agent->register_call_slot != NULL) {
```
Comment (engelmi) [inline src/agent/agent.c:547]: I am not sure this is the right place to unref the register call slot. The slot should be unrefed when 
- the heartbeat timer callback triggers and we are still in connecting state
- the register callback is called

The call here will cleanup the slot after a successful register and next heartbeat trigger after that.

File: src/libbluechi/bus/bus.c [hunk 5]
```diff
@@ -75,15 +75,18 @@ sd_bus *peer_bus_open(sd_event *event, const char *dbus_description, const char
...
+        if (*peer_dbus != NULL) {
+                bc_log_debug("Closing peer bus");
+                int r = sd_bus_detach_event(*peer_dbus);
                 if (r < 0) {
                         bc_log_errorf("Failed to detach bus from event: %s", strerror(-r));
                         return r;
                 }
 
-                sd_bus_flush_close_unref(peer_dbus);
+                sd_bus_close(*peer_dbus);
```
Comment (engelmi) [inline src/libbluechi/bus/bus.c]: You can use the convenience function `sd_bus_close_unref` here.

File: src/libbluechi/bus/bus.c [hunk 6]
```diff
@@ -75,15 +75,18 @@ sd_bus *peer_bus_open(sd_event *event, const char *dbus_description, const char
         return steal_pointer(&dbus);
 }
 
-int peer_bus_close(sd_bus *peer_dbus) {
-        if (peer_dbus != NULL) {
-                int r = sd_bus_detach_event(peer_dbus);
+int peer_bus_close(sd_bus **peer_dbus) {
```
Comment (engelmi) [inline src/libbluechi/bus/bus.c]: NIT: I'd probably keep the signature here and do `peer_dbus=NULL` in the calling function as I wouldn't expect a close function to NULL as well (`sd_bus_close` doesn't do this as well).

File: src/agent/agent.c [hunk 7]
```diff
@@ -2694,54 +2705,21 @@ void agent_stop(Agent *agent) {
...
-                        NULL,
-                        INTERNAL_AGENT_OBJECT_PATH,
-                        INTERNAL_AGENT_INTERFACE,
-                        internal_agent_vtable,
-                        agent);
-        if (r < 0) {
-                bc_log_errorf("Failed to add agent vtable: %s", strerror(-r));
-                return false;
-        }
+static int agent_process_register_callback(sd_bus_message *m, Agent *agent) {
```
Comment (engelmi) [inline src/agent/agent.c]: You can return a `bool` here since the only thing how we can react on failure is logging (which is done here). Currently, the returned `r` is used in the calling function `agent_register_callback` only for a yes/no decision and the return value of this callback function is just for sdbus to know if further callback should be triggered.

File: src/agent/agent.h [hunk 8]
```diff
@@ -82,6 +83,7 @@ struct Agent {
         sd_bus *peer_dbus;
 
         bool metrics_enabled;
+        sd_bus_slot *register_call_slot;
         sd_bus_slot *metrics_slot;
```
Comment (engelmi) [inline src/agent/agent.h]: NIT: The `register_call_slot` isn't really related to the metrics, so I'd keep it separate.
```suggestion
        sd_bus_slot *register_call_slot;

        bool metrics_enabled;
        sd_bus_slot *metrics_slot;
```

File: src/agent/agent.c [hunk 9]
```diff
@@ -2802,6 +2780,71 @@ static bool agent_connect(Agent *agent) {
...
+        Agent *agent = (Agent *) userdata;
+
+        if (agent->connection_state != AGENT_CONNECTION_STATE_CONNECTING) {
+                bc_log_error("Agent is not in CONNECTING state, dropping Register callback");
+                if (agent->register_call_slot != NULL) {
+                        sd_bus_slot_unrefp(&agent->register_call_slot);
+                        agent->register_call_slot = NULL;
+                }
+                return -EPERM;
+        }
```
Comment (engelmi) [inline src/agent/agent.c]: If we'd just do an unref + NULL here by default, we wouldn't need to check the state, right?

File: src/agent/agent.c [hunk 10]
```diff
@@ -2802,6 +2780,71 @@ static bool agent_connect(Agent *agent) {
...
+        int r = 0;
+        r = agent_process_register_callback(m, agent);
+        if (r < 0) {
+                agent->connection_state = AGENT_CONNECTION_STATE_RETRY;
```
Comment (engelmi) [inline src/agent/agent.c:2802]: NIT: I think it would be good for readability to set the connection state in only one function. So setting it at the top of  `agent_process_register_callback` to RETRY should be fine. Then you can reduce this part here as well to just calling `agent_process_register_callback` (so we always return always 0 here, which is fine since its a callback).

File: src/agent/agent.c (hunk 4 above)
Comment (mkemel) [reply src/agent/agent.c:547]: This function runs on agent shutdown, so in case we didn't get register callback when shutting down - we unref the slot

File: src/agent/agent.c (hunk 3 above)
Comment (mkemel) [reply src/agent/agent.c:548]: No need, we are freeing the agent in a short while. Note that we don't null any other objects here

File: src/agent/agent.c (hunk 7 above)
Comment (mkemel) [reply src/agent/agent.c]: By sdbus specification, callback returns `int` , i.e. `errno`. So we need this function to return int to propagate error codes

File: src/agent/agent.h (hunk 8 above)
Comment (mkemel) [reply src/agent/agent.h]: Right. Mess created by rebase

File: src/libbluechi/bus/bus.c (hunk 5 above)
Comment (mkemel) [reply src/libbluechi/bus/bus.c]: Ack, thanks

File: src/libbluechi/bus/bus.c (hunk 6 above)
Comment (mkemel) [reply src/libbluechi/bus/bus.c]: Makes sense

File: src/agent/agent.c (hunk 4 above)
Comment (engelmi) [reply src/agent/agent.c:547]: Ups, this is a change in `agent_unref` - I thought it was in the `agent_heartbeat_timer_callback`. Yes, in `agent_unref` its well placed.

File: src/agent/agent.c (hunk 3 above)
Comment (engelmi) [reply src/agent/agent.c:548]: Same as above: Thought it was the timer callback, sorry about that :sweat:

Comment (mkemel) [reply src/agent/agent.c:548]: No worries, keeps me sharp :)

File: src/agent/agent.c (hunk 7 above)
Comment (mkemel) [reply src/agent/agent.c]: So turns out it's not `errno`.
Done

File: src/agent/agent.c (hunk 9 above)
Comment (mkemel) [reply src/agent/agent.c]: Actually we can drop the `AGENT_CONNECTION_STATE_CONNECTING` with just checking if `register_call_slot` is not NULL. But I thought that it is more clear to have another state for the `connection_state` since it is really a separate state.

We can drop the NULL check though

File: src/agent/agent.c (hunk 10 above)
Comment (mkemel) [reply src/agent/agent.c:2802]: I'd leave it as it is. I think that setting the `connection_state` to `RETRY` might simplify the code, but if I would look at it without being familiar with it - I would wonder why is the state set in the beginning of the callback.
This way it is clear that it is set only when the callback handling fails

File: src/agent/agent.c (hunk 9 above)
Comment (mkemel) [reply src/agent/agent.c]: Dropped the NULL check

**Review by engelmi — APPROVED** [review]
LGTM
Great work!
